CREATE TABLE ROLE (
  role_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  description VARCHAR(60) NULL,
  alias VARCHAR(10) NULL,
  PRIMARY KEY(role_id)
);

CREATE TABLE OPTION_TYPE (
  type_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  description VARCHAR(60) NULL,
  alias VARCHAR(10) NULL,
  PRIMARY KEY(type_id)
);

CREATE TABLE AUTHORITY (
  authority_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  description VARCHAR(20) NULL,
  PRIMARY KEY(authority_id)
);

CREATE TABLE UUSER (
  user_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  ppasword VARCHAR(256) NULL,
  enabled BOOL NULL,
  user_expired_date DATE NULL,
  credentials_expired_date DATE NULL,
  end_lock_date DATE NULL,
  email VARCHAR(60) NULL,
  email_confirmed BOOL NULL,
  firstname VARCHAR(100) NULL,
  lastname VARCHAR(100) NULL,
  PRIMARY KEY(user_id)
);

CREATE TABLE AUDIT_TRAIL_TYPE (
  type_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  description VARCHAR(60) NULL,
  alias VARCHAR(10) NULL,
  PRIMARY KEY(type_id)
);

CREATE TABLE PASSWORD_HISTORY (
  pwd_history_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INTEGER UNSIGNED NOT NULL,
  ppasword VARCHAR(100) NULL,
  date DATE NULL,
  PRIMARY KEY(pwd_history_id),
  FOREIGN KEY(user_id)
    REFERENCES UUSER(user_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE OOPTION (
  option_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  parent_id INTEGER UNSIGNED NOT NULL,
  type_id INTEGER UNSIGNED NOT NULL,
  description VARCHAR(60) NULL,
  alias VARCHAR(10) NULL,
  url VARCHAR(60) NULL,
  sequence INTEGER UNSIGNED NULL,
  icon VARCHAR(60) NULL,
  parameter VARCHAR(100) NULL,
  visible BOOL NULL,
  PRIMARY KEY(option_id),
  FOREIGN KEY(type_id)
    REFERENCES OPTION_TYPE(type_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(parent_id)
    REFERENCES OOPTION(option_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE USER_ROLE (
  user_id INTEGER UNSIGNED NOT NULL,
  role_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(user_id, role_id),
  FOREIGN KEY(user_id)
    REFERENCES UUSER(user_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(role_id)
    REFERENCES ROLE(role_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE AUDIT_TRAIL (
  id_trail INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  type_id INTEGER UNSIGNED NOT NULL,
  user_id INTEGER UNSIGNED NOT NULL,
  id_entity INTEGER UNSIGNED NULL,
  entity VARCHAR(60) NULL,
  date DATE NULL,
  changes VARCHAR(4000) NULL,
  entity_before VARCHAR(4000) NULL,
  entity_after VARCHAR(4000) NULL,
  ip_address VARCHAR(60) NULL,
  mac_address VARCHAR(60) NULL,
  additional_info VARCHAR(200) NULL,
  parameters VARCHAR(4000) NULL,
  PRIMARY KEY(id_trail),
  FOREIGN KEY(user_id)
    REFERENCES UUSER(user_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(type_id)
    REFERENCES AUDIT_TRAIL_TYPE(type_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE ROLE_AUTHORITY (
  authority_id INTEGER UNSIGNED NOT NULL,
  role_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(authority_id, role_id),
  FOREIGN KEY(authority_id)
    REFERENCES AUTHORITY(authority_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(role_id)
    REFERENCES ROLE(role_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE ROLE_OPTION (
  role_id INTEGER UNSIGNED NOT NULL,
  option_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(role_id, option_id),
  FOREIGN KEY(role_id)
    REFERENCES ROLE(role_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(option_id)
    REFERENCES OOPTION(option_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


